### ISSUE TITLE
create event bug

### ISSUE THREAD

**Issue by filipzava** [GeoSmartCity-CIP/crowd-sourcing#2]
After "create event" is called this message is sent:

om.intergraph.cs.servlet.UnsupportedValueException: Unsupported status 'created'
    at com.intergraph.cs.servlet.CrowdSourcingServlet.checkStatus(CrowdSourcingServlet.java:366)
    at com.intergraph.cs.servlet.EventCreateServlet.doPost(EventCreateServlet.java:80)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:646)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
    at org.apache.catalina.filters.CorsFilter.handleSimpleCORS(CorsFilter.java:302)
    at org.apache.catalina.filters.CorsFilter.doFilter(CorsFilter.java:170)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
    at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)
    at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
    at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:503)
    at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:170)
    at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
    at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:950)
    at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
    at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:421)
    at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1070)
    at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:611)
    at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:316)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
    at java.lang.Thread.run(Thread.java:745)

**Comment by rszturc** [comment]
Fixed by issue #1. Use request /config to get list of available statuses.

**Comment by filipzava** [comment]
I downloaded the version 1.2 and this issue lasts. It looks like the status "created" is still missing. This is output of config: 

{"priorities":["normal","low","high"],"statuses":["submitted","assigned","solved","closed"],"mime_types":["image\/jpeg"],"tags":["water rupture","sewage obstruction"]}

**Comment by filipzava** [comment]
solved ;)
